import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Slider from "../components/Slider";
import Camarche from "../components/camarche";
import Map from "../components/map";
import Partenaire from "../components/partenaire";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
      <Navbar/>
      <Slider/>
      <div className="flex flex-col justify-center items-center">
        <h1 className="mt-5 text-2xl font-semibold"> COMMENT CA MARCHE</h1>
        <div className="flex flex-col lg:flex-row ">
        <Camarche text='1' logo='logo'/>
      <Camarche text='2' logo='logo'/>
      <Camarche text='3' logo='logo'/>

        </div>

      </div>

      <div className = "flex flex-col justify-center items-center">
        <h1 className="m-5 text-2xl font-semibold"> ZONE DE LIVRAISON  </h1>
        <Map/>
      </div>

      <div className = "flex flex-col justify-center items-center">
        <h1 className="m-5 text-2xl font-semibold uppercase mb-5"> Devenir partenaire  </h1>
        <Partenaire/>
      </div>

      <div>
        <Footer/>
      </div>
     </main>
    </>
  );
};

export default Home;

